from pydantic import BaseModel, Field
from typing import List, Optional

class Question(BaseModel):
    question: str = Field(..., description="The diagnostic question text")
    sub_concept: str = Field(..., description="The specific sub-concept the question addresses")
    difficulty: str = Field(..., description="The difficulty level of the question")
    question_type: str = Field(..., description="The type of question (conceptual, application, reasoning, etc.)")
    options: Optional[List[str]] = Field(default=None, description="List of options if multiple choice, otherwise None")
    correct_answer: str = Field(..., description="The correct answer to the question")
    explanation: str = Field(..., description="A concise explanation of why the answer is correct")

class DiagnosticResponse(BaseModel):
    thinking_process: Optional[str] = Field(default="", description="Dynamic step-by-step thinking & reasoning trace generated by the agent.")
    used_rag: bool = Field(default=True, description="Whether syllabus RAG context was relevant and used.")
    questions: List[Question] = Field(
        ..., 
        min_length=5, 
        max_length=5, 
        description="Exactly 5 diagnostic questions"
    )

class DiagnosisResponse(BaseModel):
    thinking_process: Optional[str] = Field(default="", description="Dynamic step-by-step thinking & reasoning trace generated by the agent.")
    has_misconception: bool = Field(..., description="True if a misconception is identified based on at least TWO relevant incorrect response patterns.")
    sub_concept: Optional[str] = Field(default=None, description="The sub-concept related to the misconception, if any.")
    misconception: Optional[str] = Field(default=None, description="The identified conceptual misunderstanding.")
    evidence: List[str] = Field(..., description="Evidence backing the diagnosis (referencing specific questions/responses) or explaining why evidence is insufficient.")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence level between 0 and 1. Does not override minimum evidence requirement.")
    affected_question_ids: List[str] = Field(default_factory=list, description="List of question identifiers (e.g., 'Q1') that provide evidence.")

class RemediationResponse(BaseModel):
    thinking_process: Optional[str] = Field(default="", description="Dynamic step-by-step looping reasoning trace generated by the remediation agent.")
    sub_concept: str = Field(..., description="The sub-concept being remediated.")
    misconception: str = Field(..., description="The misconception being addressed.")
    explanation: str = Field(..., description="Explanation of the correct concept, contrasting with the likely incorrect mental model.")
    example: str = Field(..., description="A small example demonstrating the correct concept.")
    key_takeaway: str = Field(..., description="A short, memorable key takeaway summarizing the correct concept.")
    check_question: str = Field(..., description="A short 'check your understanding' question (without giving away the answer directly).")

class AdaptiveStrategyResponse(BaseModel):
    thinking_process: Optional[str] = Field(default="", description="Dynamic step-by-step reasoning trace of adaptive strategy agent.")
    cycle_limit_reached: bool = Field(default=False, description="True if the maximum remediation cycles have been reached.")
    sub_concept: Optional[str] = Field(default=None, description="The sub-concept being addressed.")
    misconception: Optional[str] = Field(default=None, description="The specific misconception.")
    previous_strategy: Optional[str] = Field(default=None, description="The strategy that was used previously.")
    new_strategy: Optional[str] = Field(default=None, description="The new strategy to be used, differing meaningfully from the previous one.")
    rationale: Optional[str] = Field(default=None, description="Why the previous strategy might have failed and why the new strategy is better suited based on the evidence.")
    instructional_approach: Optional[str] = Field(default=None, description="Specific pedagogical approach (e.g., concrete analogy, step-by-step problem solving).")
    key_focus: Optional[str] = Field(default=None, description="The primary concept or contrast the remediation should focus on.")

class VerificationQuestion(BaseModel):
    question: str = Field(..., description="The verification question text")
    sub_concept: str = Field(..., description="The specific sub-concept being verified")
    options: List[str] = Field(..., description="List of 4 multiple-choice options")
    correct_answer: str = Field(..., description="The correct answer option number or text (e.g., '1', '2', '3', or '4')")
    explanation: str = Field(..., description="Explanation of why the answer is correct")

class VerificationResponse(BaseModel):
    thinking_process: Optional[str] = Field(default="", description="Dynamic step-by-step reasoning trace of verification agent.")
    questions: List[VerificationQuestion] = Field(
        ..., 
        min_length=2, 
        max_length=2, 
        description="Exactly 2 verification questions targeting the remediated misconception"
    )


